#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar mako mpd xfce-polkit nm-applet)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 "${_prs}"
	fi
done

# Polkit agent
/usr/lib/xfce-polkit/xfce-polkit &

# Set wallpaper
# swww-daemon
# swww img ~/.config/wallpaper/xc2_day.gif
mpvpaper -o "no-audio --loop-playlist" "*" ~/.config/wallpaper/xc2_night.mp4 &

# Apply themes
# ~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
sh ~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
sh ~/.config/hypr/scripts/statusbar &

nm-applet &

# clipboard manager
wl-paste --type text --watch cliphist store & # Stores only text data
wl-paste --type image --watch cliphist store & # Stores only image data

# Start mpd
# exec mpd &

slack &
discord &
