#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar mako mpd xfce-polkit nm-applet)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 "${_prs}"
	fi
done

# Polkit agent
/usr/lib/xfce-polkit/xfce-polkit &

# Set wallpaper
swaybg --output '*' --mode fill --image ~/.config/wallpaper/xenoblade3.jpg &

# Apply themes
# ~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
sh ~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
sh ~/.config/hypr/scripts/statusbar &

nm-applet &

# clipboard manager
wl-paste --type text --watch cliphist store & # Stores only text data
wl-paste --type image --watch cliphist store & # Stores only image data

# Start mpd
# exec mpd &

slack &
discord &
